### ISSUE TITLE
May be a nanomsg's bug that caused program crash

### ISSUE THREAD

**Issue by xiaopidanO** [nanomsg/nanomsg#1114]
This is the stack info：
#0  0x00007fb100ef337f in raise () from /usr/lib64/libc.so.6
#1  0x00007fb100edddb5 in abort () from /usr/lib64/libc.so.6
#2  0x000000000067b7b2 in nn_err_abort () at /nanomsg-1.1.5/src/utils/err.c:56
#3  0x000000000069c794 in nn_usock_init_from_fd (self=0xe33fe8, s=14) at /nanomsg-1.1.5/src/aio/usock_posix.inc:195
#4  0x000000000069c6c5 in nn_usock_start (self=0xe33fe8, domain=2, type=524289, protocol=0) at /nanomsg-1.1.5/src/aio/usock_posix.inc:175
#5  0x0000000000691308 in nn_ctcp_start_connecting (self=0xe33f80, ss=0xe348b0, sslen=16) at /nanomsg-1.1.5/src/transports/tcp/ctcp.c:583
#6  0x0000000000690630 in nn_ctcp_handler (self=0xe33f80, src=3, type=2, srcptr=0xe34730) at /nanomsg-1.1.5/src/transports/tcp/ctcp.c:322
#7  0x00000000006799ab in nn_fsm_feed (self=0xe33f80, src=3, type=2, srcptr=0xe34730) at /nanomsg-1.1.5/src/aio/fsm.c:83
#8  0x0000000000679966 in nn_fsm_event_process (self=0xe34760) at /nanomsg-1.1.5/src/aio/fsm.c:77
#9  0x000000000067971d in nn_ctx_leave (self=0xe33ab8) at /nanomsg-1.1.5/src/aio/ctx.c:63
#10 0x000000000067a764 in nn_worker_routine (arg=0xd55120 <self+32>) at /nanomsg-1.1.5/src/aio/worker_posix.inc:239
#11 0x000000000067ca66 in nn_thread_main_routine (arg=0xd55308 <self+520>) at /nanomsg-1.1.5/src/utils/thread_posix.inc:35
#12 0x00007fb10274117a in start_thread () from /usr/lib64/libpthread.so.0
#13 0x00007fb100fb8dc3 in clone () from /usr/lib64/libc.so.6

why nn_usock_start will enter  the wrong state NN_USOCK_STATE_STARTING and cause abort
When I read the nanomsg's code,maybe due to this reason：
when calling 'nn_ctcp_start_connecting' function in ctcp.c
It will use 'nn_usock_start'  try to start the underlying socket and make self->state = NN_CTCP_STATE_WAITING , However,  if Bind the socket to the local network interface failed through 'nn_usock_bind' in the next steps,
The code didn't call nn_usock_stop  function to recover state,  other similar failed places have call nn_usock_stop  function to recover state in code. so , I guess this maybe is a bug in nanomsg
![_20240820225443](https://github.com/user-attachments/assets/4ae182ed-7ce2-46a9-9ae4-1ae69b1436ae)

**Comment by gdamore** [comment]
Does smell a little bit like a bug indeed.

**Comment by xiaopidanO** [comment]
thanks very much



发自我的iPhone


------------------ Original ------------------
From: gdamore ***@***.***&gt;
Date: Mon,Oct 6,2025 0:48 AM
To: nanomsg/nanomsg ***@***.***&gt;
Cc: xiaopidan ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [nanomsg/nanomsg] May be a nanomsg's bug that caused programcrash (Issue #1114)





 
Closed #1114 as completed via 7c2e828.
