### ISSUE TITLE
infinite loop in worker thread

### ISSUE THREAD

**Issue by gmd20** [nanomsg/nanomsg#999]
I wrote a simple server program:
```c
int main(void)
{
  struct nn_pollfd pfd [1];

  int server_sock = nn_socket(AF_SP, NN_REP);
  if (server_sock < 0) {
    return 1;
  }
  if (nn_bind(server_sock, "ipc:///tmp/server.ipc") < 0 ) {
    return 1;
  }
  sleep(1);
  chmod("/tmp/server.ipc", 0666);

  for (;;) {
    pfd [0].fd = server_sock;
    pfd [0].events = NN_POLLIN;
    pfd [0].revents = 0;
    int rc = nn_poll(pfd, 1, 1000);

    if (rc == 0) { // Timeout
    } else if (rc == -1) {
      break;
    }

    if (pfd[0].revents & NN_POLLIN) {
      char buf[2048];
      int len = nn_recv(server_sock, buf, 2047, NN_DONTWAIT);
      if (len > 0) {
        buf[len] = '\0';
        nn_send(sock, "123456\n", 7, NN_DONTWAIT);
      }
    }
  }
  return 0;
}
```

```text
nanocat --req --connect-ipc  /tmp/server.ipc  --recv-timeout 1 --send-timeout 1 --raw --data test
```
The above command prints the reply message properly at the beginning,  but after the server
idles for several hours, this command doesn't work, nanocat exit and nothing was displayed.

The nanomsg work thread consumed all the CPU,  and
GDB show that the worker thread was doing "write" and "accept4" repeatedly.
```text
Thread 2 (Thread 0x7fd1c780c700 (LWP 27423)):
#0  0x00007fd1c813eced in write () from /lib64/libc.so.6
#1  0x00007fd1c8c578d5 in nn_efd_signal () from /usr/lib/libnanomsg.so.5
#2  0x00007fd1c8c56530 in nn_worker_execute () from /usr/lib/libnanomsg.so.5
#3  0x00007fd1c8c53803 in nn_usock_accept () from /usr/lib/libnanomsg.so.5
#4  0x00007fd1c8c6a43e in nn_aipc_handler () from /usr/lib/libnanomsg.so.5
#5  0x00007fd1c8c51827 in nn_fsm_feed () from /usr/lib/libnanomsg.so.5
#6  0x00007fd1c8c517e3 in nn_fsm_event_process () from /usr/lib/libnanomsg.so.5
#7  0x00007fd1c8c515b3 in nn_ctx_leave () from /usr/lib/libnanomsg.so.5
#8  0x00007fd1c8c56961 in nn_worker_routine () from /usr/lib/libnanomsg.so.5
#9  0x00007fd1c8c59720 in nn_thread_main_routine () from /usr/lib/libnanomsg.so.5
#10 0x00007fd1c7a2ee25 in start_thread () from /lib64/libpthread.so.0
#11 0x00007fd1c814dbad in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7fd1c780c700 (LWP 27423)):
#0  0x00007fd1c814f03f in accept4 () from /lib64/libc.so.6
#1  0x00007fd1c8c553dc in nn_usock_handler () from /usr/lib/libnanomsg.so.5
#2  0x00007fd1c8c51827 in nn_fsm_feed () from /usr/lib/libnanomsg.so.5
#3  0x00007fd1c8c5694d in nn_worker_routine () from /usr/lib/libnanomsg.so.5
#4  0x00007fd1c8c59720 in nn_thread_main_routine () from /usr/lib/libnanomsg.so.5
#5  0x00007fd1c7a2ee25 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fd1c814dbad in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fd1c92af740 (LWP 27421)):
#0  0x00007fd1c8142f0d in poll () from /lib64/libc.so.6
#1  0x00007fd1c8c4e2d4 in nn_poll () from /usr/lib/libnanomsg.so.5
#2  0x0000000000401a84 in main ()
(gdb) 

Thread 2 (Thread 0x7fd1c780c700 (LWP 27423)):
#0  0x00007fd1c814f03f in accept4 () from /lib64/libc.so.6
#1  0x00007fd1c8c553dc in nn_usock_handler () from /usr/lib/libnanomsg.so.5
#2  0x00007fd1c8c51827 in nn_fsm_feed () from /usr/lib/libnanomsg.so.5
#3  0x00007fd1c8c5694d in nn_worker_routine () from /usr/lib/libnanomsg.so.5
#4  0x00007fd1c8c59720 in nn_thread_main_routine () from /usr/lib/libnanomsg.so.5
#5  0x00007fd1c7a2ee25 in start_thread () from /lib64/libpthread.so.0
#6  0x00007fd1c814dbad in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fd1c92af740 (LWP 27421)):
#0  0x00007fd1c8142f0d in poll () from /lib64/libc.so.6
#1  0x00007fd1c8c4e2d4 in nn_poll () from /usr/lib/libnanomsg.so.5
#2  0x0000000000401a84 in main ()
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x00007fd1c8142f0d in poll () from /lib64/libc.so.6
(gdb) thread  apply all bt

Thread 2 (Thread 0x7fd1c780c700 (LWP 27423)):
#0  0x00007fd1c814e12a in epoll_ctl () from /lib64/libc.so.6
#1  0x00007fd1c8c7e219 in nn_poller_add () from /usr/lib/libnanomsg.so.5
#2  0x00007fd1c8c56192 in nn_worker_add_fd () from /usr/lib/libnanomsg.so.5
#3  0x00007fd1c8c53fc5 in nn_internal_tasks () from /usr/lib/libnanomsg.so.5
#4  0x00007fd1c8c5438b in nn_usock_handler () from /usr/lib/libnanomsg.so.5
#5  0x00007fd1c8c51827 in nn_fsm_feed () from /usr/lib/libnanomsg.so.5
#6  0x00007fd1c8c568e7 in nn_worker_routine () from /usr/lib/libnanomsg.so.5
#7  0x00007fd1c8c59720 in nn_thread_main_routine () from /usr/lib/libnanomsg.so.5
#8  0x00007fd1c7a2ee25 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fd1c814dbad in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7fd1c92af740 (LWP 27421)):
#0  0x00007fd1c8142f0d in poll () from /lib64/libc.so.6
#1  0x00007fd1c8c4e2d4 in nn_poll () from /usr/lib/libnanomsg.so.5
#2  0x0000000000401a84 in main ()
(gdb) 
```

I don't understand why nanomsg is still "accepting and writing" on the socket after the nanocat exits 
for a long time(no active or new connections).

OS:  CentOS 7.5
nanomsg v1.1.5

**Comment by gmd20** [comment]
There is a bug in my program,  too many fds are opened but never being fclosed,  so at some point it reaches the "max open file limit" and accept4 always return -1 (errno -24). 

```text
    /*  Some errors are just ok to ignore for now.  We also stop repeating
        any errors until next IN_FD event so that we are not in a tight loop
        and allow processing other events in the meantime  */
    if (nn_slow (errno != EAGAIN && errno != EWOULDBLOCK
        && errno != ECONNABORTED && errno != listener->errnum))   // errno ==  listener->errnum == -24 at this line
    {
        listener->errnum = errno;
        listener->state = NN_USOCK_STATE_ACCEPTING_ERROR;
        nn_fsm_raise (&listener->fsm,
            &listener->event_error, NN_USOCK_ACCEPT_ERROR);
        return;
    }
```
.
